#!/usr/bin/env python
# Based on the code by Christo Venter in Matlab (King.m)
# Author : Bertie Seyffert
# This is also intended to be used with the notes for this experiment
# for 2018. Subsequent changes aren't reflected.



import argparse
import numpy as np
import matplotlib.pyplot as plt

from scipy.special import erf
from scipy.integrate import simps

from astropy import constants as const
G = const.G.cgs.value
pc = const.pc.cgs.value
M_sun = const.M_sun.cgs.value







# ==== ==== ==== ==== Arguments ==== ==== ==== ====
# ---- Parse ----
parser = argparse.ArgumentParser()

# Positional (mandatory) arguments
parser.add_argument(
    'W_0', type=np.float64,
    help='Scaled potential at r = 0'
)

# Optional arguments
parser.add_argument(
    '-d', '--data', default=None, type=str,
    help=('Takes a filename as input. The values of R and sigma profile '
          'will be read from column 0 and 1 by default (0 counted.)'
          'To give column number of your choice use arguments dcR and dcS.')
)
parser.add_argument(
    '--dcR',  default=0, type=int,
    help=('Takes column number for R in file given in argument "data". '
          'Beware that column 0 is counted. [default: %(default).2g]')
)
parser.add_argument(
    '--dcS',  default=1, type=int,
    help=('Takes column number for sigma profile in file given in argument "data".'
          'Beware that column 0 is counted. [default: %(default).2g]')
)
parser.add_argument(
    '-o', '--output', default=None, type=str,
    help=('Takes a filename as input. The calculated surface brightness '
          'profile will be saved to this file. The profile is normalised '
          'before saving.')
)
parser.add_argument(
    '-r', '--reference', default=None, type=str,
    help=('Takes a filename as input. The surface brightness profile '
          'contained in this file will be plotted alongside the calculated '
          'surface brightness profile. Expects a file generated by king.py '
          'through --output.')
)
parser.add_argument(
    '--dR', default=0.01, type=np.float64,
    help='Step length for dimensionless R [default: %(default).2g]'
)
parser.add_argument(
    '--v_disp', default=6.4e5, type=np.float64,
    help='Velocity dispersion in cm/s [default: %(default).2g]'
)
parser.add_argument(
    '--distance', default=8.5e3, type=np.float64,
    help='Distance to the cluster in pc [default: %(default).2g]'
)
parser.add_argument(
    '--r_core', default=0.18, type=np.float64,
    help='Core radius in arcminutes [default: %(default).2g]'
)
parser.add_argument(
    '--rho_0_infered', default=1e3, type=np.float64,
    help='Infered core density in M_sun/(pc^3) [default: %(default).2g]'
)

# Switches
parser.add_argument(
    '-m', '--mass', action='store_true',
    help='If set, the mass of the cluster is output'
)
parser.add_argument(
    '-s', '--suppress', action='store_true',
    help='If set, no graphs will be plotted'
)

args = parser.parse_args()

# ---- Convert to cgs ----
args.distance *= pc
args.r_core = np.deg2rad(args.r_core/60.)*args.distance
args.rho_0_infered *= M_sun/np.power(pc, 3)
# v_disp is already in cgs

# ==== ==== ==== ==== Set up calculation ==== ==== ==== ====
def calcRho_over_k(W):
    return (
        np.pi*np.power(np.sqrt(2)*args.v_disp, 3)
        *(np.sqrt(np.pi)*np.exp(W)*erf(np.sqrt(W)) - 2*np.sqrt(W)*(W*2/3. + 1))
    )

def calcW(R_i, W_im1, W_i, rho_0, rho_i):
    # im1 denotes i-1 ("_i[ ]m[inus ]1")
    # rho_i is in units of k (the same as rho_0)
    F_0 = 4*np.pi*G*args.rho_0_infered*np.square(args.r_core/args.v_disp)
    return (
        (2*W_i - (1 - args.dR/R_i)*W_im1 - F_0*args.dR**2*rho_i/rho_0)
        /(1. + args.dR/R_i)
    )

# ---- Initialise variables (including F_0) ----
R = np.array([0.])
W = np.array([args.W_0])
rho_over_k = np.array([calcRho_over_k(W=W[0])])

R = np.append(R, R[0]+args.dR)

# Implied by dW/dR (0) = 0
W = np.append(W, W[0])

# rho_over_k is a function of W, so this follows from the above...
rho_over_k = np.append(rho_over_k, rho_over_k[0])

# ==== ==== ==== ==== Calculate sigma(R) ==== ==== ==== ====
# ---- Calculate W(R) and rho_over_k(R) ----
W = np.append(W, calcW(R_i=R[-1], W_im1=W[-2], W_i=W[-1],
                       rho_0=rho_over_k[0], rho_i=rho_over_k[-1]))

while W[-1] > 0.0:
    rho_over_k = np.append(rho_over_k, calcRho_over_k(W=W[-1]))
    R = np.append(R, R[-1] + args.dR)
    W = np.append(W, calcW(R_i=R[-1], W_im1=W[-2], W_i=W[-1],
                           rho_0=rho_over_k[0], rho_i=rho_over_k[-1]))

# The last element of W will be < 0 by construction
W = np.delete(W, W.size-1)
print ('Tidal radius: {0} pc'.format(R[-1]*args.r_core/pc))

# ---- Integrate over R to obtain sigma(R) ----
# NOTE: This R is technically a different R. We choose to use the same spacing
#       for convenience.
sigma = np.empty(R.size-1)
for index, r in enumerate(R[:-1]):
    sigma[index] = 2*simps(
        y=(R[index+1:]/np.sqrt(np.square(R[index+1:]) - np.square(R[index])))
        *rho_over_k[index + 1:],
        x=R[index+1:]
    )
sigma /= sigma.max()

# ==== ==== ==== ==== Derive Mass ==== ==== ==== ====
# For the next bit we need R in cm...
R *= args.r_core

if args.mass:
    rho = (args.rho_0_infered/rho_over_k[0])*rho_over_k
    M_total = 4.*np.pi*simps(y=np.square(R)*rho, x=R)/M_sun
    print ('Total mass of cluster: {0} M_sun'.format(M_total))

# ==== ==== ==== ==== Scale to data and save profile ==== ==== ==== ====
# This needs to come before the saving step since it scales sigma

if args.data is not None:
    dataR, dataSigma = np.loadtxt(
        args.data, usecols=(args.dcR, args.dcS), unpack=True     
    )

    # Scale model sigma to lie between dataSigma.max() and dataSigma.min()
    sigma = sigma*dataSigma.ptp() + dataSigma.min()

# Now we need R in parsec
R /= pc

#++++++++ChatGPT suggestion begin

#print("R.shape:", R.shape)
#print("sigma.shape:", sigma.shape)
#print("sigma[:5]:", sigma[:5])
#print("Any NaNs in sigma?", np.isnan(sigma).any())
#print("sigma.max():", sigma.max())

#+++++++ChatGPT suggestion end


if args.output is not None:

# +++++ ChatGPT suggestion to comment out the next line and add the current line
#    np.savetxt(args.output, zip(R, sigma), fmt='%1.4g')
     np.savetxt(args.output, np.column_stack((R[:-1], sigma)), fmt='%1.4g')

# +++++ ChatGPT suggestion end

    #np.savetxt(args.output, zip(R, sigma), fmt='%1.4g', delimiter=',')



# ==== ==== ==== ==== Plot profiles ==== ==== ==== ====
# ---- Import previously generated profile ----
if args.reference is not None:
    refR, refSigma = np.loadtxt(args.reference, unpack=True)
    #refR, refSigma = np.loadtxt(args.reference, delimiter=',', unpack=True)
    refSigma -= refSigma.min()
    refSigma /= refSigma.max()

    # Scale reference profile to correspond to calculated profile
    refSigma = refSigma*sigma.ptp() + sigma.min()

# ---- Plot surface brightness profile(s) ----
if not args.suppress:
    plt.plot(R[:-1], sigma/sigma.max(),
             label='Model profile')
    xmax = R.max()

    if args.reference is not None:
        plt.plot(refR, refSigma/refSigma.max(), color='green',
                 label='Model profile (reference)')
        xmax = np.maximum(xmax, refR.max())

    if args.data is not None:
        plt.plot(dataR, dataSigma/dataSigma.max(), 'o',
                 label='Observed profile')
        xmax = np.maximum(xmax, dataR.max())

    plt.title('Surface brightness vs. Radius')
    plt.xlabel('R (pc)')
    plt.ylabel('Surface brightness (normalised)')
    plt.xlim(0, 1.1*xmax)
    plt.ylim(0, 1.1)
    plt.legend(loc=1)
    plt.show()
